#!/bin/sh
xrandr --output eDP-1 --mode 2240x1400 --pos 0x864 --rotate normal --output HDMI-1 --primary --mode 2560x1440 --pos 2240x0 --rotate normal --output DP-1 --off --output DP-2 --off --output DP-3 --off --output DP-4 --off
betterlockscreen -u "$HOME/.config/awesome/nord.jpg" --fx

