#!/bin/sh
xrandr --output eDP-1 --primary --mode 1920x1080 --pos 760x1440 --rotate normal --output HDMI-1 --off --output DP-1 --off --output DP-2 --mode 3440x1440 --pos 0x0 --rotate normal --output DP-3 --off --output DP-4 --off
betterlockscreen -u "$HOME/.config/awesome/nord.jpg" --fx
