# User swayidle configuration
# Overrides /usr/share/sway/config.d/90-swayidle.conf
#
# Custom timeouts:
# - Lock after 15 minutes (900 seconds) of inactivity
# - Turn off display 30 seconds after lock

exec LT="$lock_timeout" ST="$screen_timeout" LT=${LT:-900} ST=${ST:-30} && \
    swayidle -w \
        timeout $LT 'swaylock -f' \
        timeout $((LT + ST)) 'swaymsg "output * power off"' \
                      resume 'swaymsg "output * power on"'  \
        timeout $ST 'pgrep -xu "$USER" swaylock >/dev/null && swaymsg "output * power off"' \
             resume 'pgrep -xu "$USER" swaylock >/dev/null && swaymsg "output * power on"'  \
        before-sleep 'swaylock -f' \
        lock 'swaylock -f' \
        unlock 'pkill -xu "$USER" -SIGUSR1 swaylock'
